SvnError: change to empty struct
It makes more sense to have an empty struct than an enum with only
one variant, since there is only one possible source of errors
(see, for instance, std::syn::mpsc::RecvError)